"""Update unique constraint credential table

Revision ID: 84811be2cda7
Revises: eed36ae3c79a
Create Date: 2025-11-23 21:06:27.350751

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '84811be2cda7'
down_revision = 'eed36ae3c79a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_credential_org_project_provider'), 'credential', type_='unique')
    op.create_unique_constraint('uq_credential_project_provider_is_active', 'credential', ['project_id', 'provider', 'is_active'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_credential_project_provider_is_active', 'credential', type_='unique')
    op.create_unique_constraint(op.f('uq_credential_org_project_provider'), 'credential', ['organization_id', 'project_id', 'provider'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
